### ISSUE TITLE
Issue with USDT Perp Liquidation_Stream

### ISSUE THREAD

**Issue by bryanplace86** [bybit-exchange/pybit#44]
I've spent several hours trying to figure this roadblock out but haven't had any luck. I'm somewhat new to pybit so hopefully this is a simple fix. I'm trying to consume the usdt perp liquidation stream. My results have been fairly inconsistent. 

When I run the following code, I am able to print the liquidation stream to the console:
![image](https://user-images.githubusercontent.com/26605280/178556133-361757d1-601b-4c93-83b8-f5d917de8e5c.png)

If I try to manipulate the websocket feed, I don't get any response from the websocket nor does it print the liquidation stream to console:
![image](https://user-images.githubusercontent.com/26605280/178556851-6a24cc52-f741-45bb-b740-df01b209efc2.png)

Any ideas would be appreciated!

**Comment by aoki-h-jp** [comment]
@bryanplace86 
I'm struggling with this issue right now. How did you solve it?

**Comment by dextertd** [comment]
Pybit has moved on significantly since this issue. I would suggest passing `trace_logging=True` when setting up the websocket object so that you can see the traffic. The trouble with the liquidation websocket is that liquidations are not that common, so you won't actually get much information from it. So you can have a look at the trace logs and open a new issue if you still see a problem.

**Comment by aoki-h-jp** [comment]
@dextertd 
Thank you for your helpful comments.
This issue was critical for me as I wanted to build a trading strategy using liquidation.
If there seems to be a problem after looking at the situation for a while, I will open a new issue.
